stages:
  - build
  - deploy staging
  - deploy_inn

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG
  STAGING_APP: test
  PRODUCTION_APP: test

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker images
    - docker push $IMAGE_TAG

deploy_inn:
  stage: deploy_inn
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker pull $IMAGE_TAG
    - cp ./docker-compose.yaml /home
    - docker-compose pull
    - docker-compose stop test || true
    - docker-compose up -d --force-recreate
  when: manual
  tags:
    - shell 
